### ISSUE TITLE
OPC-UA example from README not working

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1012]
I tried to run the OPC-UA example `demo-opcua1.ts` from [README](https://github.com/eclipse-thingweb/node-wot/blob/master/packages/binding-opcua/README.md) (see [gist](https://gist.github.com/danielpeintner/e6c0f3723dce910f2dfcb8128f10b964) for full code).

When trying to run it I get the following error

```
Cannot figure out field category for  { name: 'value', fieldType: 'Variant', defaultValue: null }
...\node_modules\node-opcua-factory\dist\builtin_types.js:262
        throw new Error("Cannot find schema for simple type " + name);
```

The issue seems to come from [node-opcua](https://www.npmjs.com/package/node-opcua) and not from node-wot code.
@erossignon do you have any advice?

**Comment by danielpeintner** [comment]
Interesting: IF I run the sample `demo-opcua1` from https://github.com/eclipse-thingweb/node-wot/blob/master/packages/examples/src/bindings/opcua/demo-opcua1.ts I get a different error...

```
D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\examples>node dist\bindings\opcua\demo-opcua1
D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:117
                    throw new Error("Cannot connected to endpoint " + endpoint + "\nmsg = " + err.message);
                          ^

Error: Cannot connected to endpoint opc.tcp://opcuademo.sterfive.com:26543
msg = The connection may have been rejected by server,
Err = (ERROR in waiting for data on socket ( timeout was = 60000 ms) undefined)
    at OPCUAProtocolClient.<anonymous> (D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:117:27)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2
```

As if the server is not reachable even though the `endpointUrl` `"opc.tcp://opcuademo.sterfive.com:26543"` is the same?

**Comment by erossignon** [comment]
opcuademo.sterfive.com was down and should be back online.

**Comment by danielpeintner** [comment]
> opcuademo.sterfive.com was down and should be back online.

Mhh, not sure if it works...

Somehow the test still does not work, running `node dist\bindings\opcua\demo-opcua1`

```
D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\examples>node dist\bindings\opcua\demo-opcua1
D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:117
                    throw new Error("Cannot connected to endpoint " + endpoint + "\nmsg = " + err.message);
                          ^

Error: Cannot connected to endpoint opc.tcp://opcuademo.sterfive.com:26543
msg = The connection may have been rejected by server,
Err = (ERROR in waiting for data on socket ( timeout was = 60000 ms) undefined)
    at OPCUAProtocolClient.<anonymous> (D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:117:27)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-opcua\dist\opcua-protocol-client.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.2
```

**Comment by danielpeintner** [comment]
> > do you have any advice?
> 
> Can you share also the package.json for your gist ?

What I would like to achieve is to run it with JS as we do with other bindings examples.
For doing so.. you can copy the [JS gist](https://gist.github.com/danielpeintner/c20319e098e5adcb571d4f37c2eb6999) in an empty folder and then

`npm install @node-wot/core`
`npm install @node-wot/binding-opcua`

--> `package.json` is automatically generated.

and run the example with 
`node demo-opcua1.js`

and you will see the error
```

D:\Projects\2023\2023-OPC-UA\test3>node demo-opcua1.js
11:18:11.488Z :structured_type_schema        :32    Cannot figure out field category for  { name: 'value', fieldType: 'Variant', defaultValue: null }
D:\Projects\2023\2023-OPC-UA\test3\node_modules\node-opcua-data-value\node_modules\node-opcua-factory\dist\builtin_types.js:262
        throw new Error("Cannot find schema for simple type " + name);
        ^

Error: Cannot find schema for simple type Variant
```

**Comment by egekorkan** [comment]
I and @hasanheroglu have observed the same behavior when trying to integrate opc ua into [WADE](https://github.com/tum-esi/wade).

**Comment by danielpeintner** [comment]
@erossignon do you have any idea how we can work around it?

**Comment by erossignon** [comment]
OK,
- @node-wot/binding-opcua relies on node-opcua-pubsub-client and other node-opcua-xx libraries.
- in @node-wot/binding-opcua, are imported with fixed version.
- node-opcua-pubsub-client is relying on peerDependencies to include its relevant node-opcua-xx library ( no version fixed)
- for this reason any node-opcua-xxx libraries used by node-opcua-pubsub-client must be declared in the package.json of the main application.
- by default, if not specified, npm use the latest version it found. 

```
        "node-opcua": "2.77.0",
        "node-opcua-address-space": "2.77.0",
        "node-opcua-basic-types": "2.77.0",
        "node-opcua-binary-stream": "2.77.0",
        "node-opcua-buffer-utils": "2.77.0",
        "node-opcua-data-model": "2.77.0",
        "node-opcua-data-value": "2.77.0",
        "node-opcua-extension-object": "2.77.0",
        "node-opcua-json": "0.19.1",
        "node-opcua-nodeid": "2.77.0",
        "node-opcua-pubsub-client": "0.19.1",
        "node-opcua-types": "2.77.0",
        "node-opcua-variant": "2.77.0"
```

from node-opcua-pubsub-client
```
    "node-opcua-basic-types": ">=2.64.0",
    "node-opcua-client": ">=2.64.0",
    "node-opcua-constants": ">=2.64.0",
    "node-opcua-data-model": ">=2.64.0",
    "node-opcua-debug": ">=2.64.0",
    "node-opcua-nodeid": ">=2.64.0",
    "node-opcua-pseudo-session": ">=2.64.0",
    "node-opcua-service-browse": ">=2.64.0",
    "node-opcua-service-translate-browse-path": ">=2.64.0",
    "node-opcua-status-code": ">=2.64.0",
    "node-opcua-types": ">=2.64.0",
    "node-opcua-variant": ">=2.64.0"
```
from node-opcua-pubsub-json
```
  "peerDependencies": {
    "node-opcua-basic-types": ">=2.64.0",
    "node-opcua-binary-stream": ">=2.64.0",
    "node-opcua-buffer-utils": ">=2.64.0",
    "node-opcua-data-model": ">=2.64.0",
    "node-opcua-data-value": ">=2.64.0",
    "node-opcua-date-time": ">=2.64.0",
    "node-opcua-debug": ">=2.64.0",
    "node-opcua-extension-object": ">=2.64.0",
    "node-opcua-factory": ">=2.64.0",
    "node-opcua-nodeid": ">=2.64.0",
    "node-opcua-numeric-range": ">=2.64.0",
    "node-opcua-status-code": ">=2.64.0",
    "node-opcua-types": ">=2.64.0",
    "node-opcua-variant": ">=2.64.0"
  },
```



those packages defined for node-opcua-pubsub-client are missing in binding-opcua or in the top-level package.json.

```
    "node-opcua-client": "2.77.0",
     "node-opcua-constants": "2.77.0",
     "node-opcua-debug": "2.77.0",
     "node-opcua-pseudo-session": "2.77.0",
     "node-opcua-service-browse": "2.77.0",
     "node-opcua-service-translate-browse-path": "2.77.0",
     "node-opcua-status-code": "2.77.0",
     "node-opcua-factory": "2.77.0",
     "node-opcua-date-time": "2.77.0",
     "node-opcua-numeric-range": "2.77.0"
```


I am going to provide a PR to fix the package.json in binding-opcua

**Comment by erossignon** [comment]
Also found out that rxjs@5.5.11 need to be explictely installed in top level package.json of the demo1.ts

**Comment by erossignon** [comment]
(interestingly , pnpm seems to do a better job at resolving none explicit module requirements than the npm version that comes with the nodejs required by node-wot (18.0) )


doing `pnpm install` instead of `npm install` doesn't exhibit the original issue.

**Comment by relu91** [comment]
I'm wondering, instead of fixing the versions in node-wot like we are doing in https://github.com/eclipse-thingweb/node-wot/pull/1019 isn't better to document this behavior and let applications install the required `peerDependecies`? Remember that `binding-opcua` is still a library, not an end-user application.

**Comment by danielpeintner** [comment]
> I'm wondering, instead of fixing the versions in node-wot like we are doing in #1019 isn't better to document this behavior and let applications install the required `peerDependecies`? Remember that `binding-opcua` is still a library, not an end-user application.

At the moment one can create a simple demo script, install dependencies like this

`npm install @node-wot/core`
`npm install @node-wot/binding-opcua`

and run `node demo-opcua.js`

I guess using `peerDependencies` makes this process more complex...

**Comment by erossignon** [comment]
> I'm wondering, instead of fixing the versions in node-wot like we are doing in https://github.com/eclipse-thingweb/node-wot/pull/1019 isn't better to document this behavior and let applications install the required peerDependecies? Remember that binding-opcua is still a library, not an end-user application.

As @danielpeintner pointed out, this would make the sample a little bit more complex to implement.
Also to get the full benefit, binding-opcua would need to reference to node-opcua-xxx libraries using also a peerDependencies, so that it would work with any version of node-opcua that the top level package has decided to installed.

For the moment, it's OK to stick to a fixed version of node-opcua required by binding-opcua and add the missing peerDependencies as proper "dependencies" in this binding-opcua module.

**Comment by relu91** [comment]
See https://github.com/eclipse-thingweb/node-wot/pull/1019#pullrequestreview-1477057281 . For that reason I think it would be better to define peerDeps also in the `binding-opcua` module in the future.

**Comment by danielpeintner** [comment]
@erossignon is it possible that `opcuademo.sterfive.com` is down is down again?

Running the sample from https://github.com/eclipse-thingweb/node-wot/issues/1012#issuecomment-1584419859 just hangs.. no timeout. It hangs for ever.

When trying to create my own server as described [here](https://github.com/node-opcua/node-opcua/blob/master/documentation/creating_a_server.md) ... I also fail since I do not really understand what I need to set for `"opcua:nodeId": "ns=1;s=PumpSpeed"` ... I tried `"opcua:nodeId": "ns=1;i=1001"` what the UAExpert tool shows .. but also without success.
SORRY nooby question 🤷‍♂️

**Comment by danielpeintner** [comment]
I think there is still an issue somewhere in the binding-opcua since I can contact the local server with `"opcua:nodeId": "ns=1;s=free_memory"` with UAExpert but NOT through node-wot.

**Comment by erossignon** [comment]
> opcuademo.sterfive.com  
 No, hte server is up and running, could it be that this route Is blocked by your network security ?
Can you ping opcuademo.sterfive.com  ?

```ping opcuademo.sterfive.com 
PING opcuademo.sterfive.com(64:ff9b::5fd8:3788 (64:ff9b::5fd8:3788)) 56 data bytes
64 bytes from 64:ff9b::5fd8:3788 (64:ff9b::5fd8:3788): icmp_seq=1 ttl=59 time=59.3 ms
64 bytes from 64:ff9b::5fd8:3788 (64:ff9b::5fd8:3788): icmp_seq=2 ttl=59 time=51.1 ms
64 bytes from 64:ff9b::5fd8:3788 (64:ff9b::5fd8:3788): icmp_seq=3 ttl=59 time=86.2 m
``̀

**Comment by danielpeintner** [comment]
Thanks for getting back to me. Yes, it seems to be a company network issue (it seems to be blocked). We will look into it...

I tried on my _private_ machine were the sample posted [above](https://github.com/eclipse-thingweb/node-wot/issues/1012#issuecomment-1588887980) worked nicely this time . The only _little_ surprise was that on the first run openssl was installed automatically.

![image](https://github.com/eclipse-thingweb/node-wot/assets/11281461/8009a92d-8cfe-479c-86cd-ab8850e5e039)

**Comment by erossignon** [comment]
@danielpeintner, 
Yes, openssl is still require in this old version of node-opcua. no

Newer version of node-opcua are now capable of generating X509 certificates directly without relying on open-sll since node-opcua> 2.105.0
However this version impose that nodejs version is greater than > 16.7 

I am not sure what are the mimumum prerequisite for nodewot ?

**Comment by danielpeintner** [comment]
> I am not sure what are the mimumum prerequisite for nodewot ?

We recently set the minimum bar for node-wot to Node.js 16

**Comment by erossignon** [comment]
this one can be closed

**Comment by danielpeintner** [comment]
@relu91 I remember you raised concerns in https://github.com/eclipse-thingweb/node-wot/pull/1019#pullrequestreview-1477057281. Do you feel we should keep this issue open for that reason?

**Comment by erossignon** [comment]
@relu91 , I would close this issue now.
