### ISSUE TITLE
InteractionOutput - no schema/schema.type and the expectations of the value() function

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1243]
PR https://github.com/eclipse-thingweb/node-wot/pull/1230 reports/fixes/adjusts the case for `schema == null` (no expected value) for `value()` function reporting `undefined` .

Anyhow, there is a much broader issue:
* what is a valid schema?
* `schema.type == null` since we use `oneof`
* optional return value
* ...

Relates also to:
* https://github.com/w3c/wot-scripting-api/pull/534
* https://github.com/w3c/wot-thing-description/issues/1441
* https://github.com/w3c/wot-thing-description/issues/1234

**Comment by egekorkan** [comment]
> what is a valid schema?

That is a big question, maybe, but anything that validates the JSON Schema meta schema is valid: https://github.com/json-schema-org/json-schema-spec/blob/draft-handrews-json-schema-validation-00/schema.json

My bigger question is why we are looking inside a data schema, it should be just "passed over". If it is validation, the whole property is a schema, with action input or output etc.

**Comment by relu91** [comment]
> My bigger question is why we are looking inside a data schema, it should be just "passed over". If it is validation, the whole property is a schema, with action input or output etc.

Because we are not using the schema just to validate the payload but also to guide the *decoding* of the payload. Basically, having the schema allows us to convert non-JSON content types to Javascript objects that can be later validated with the schema. 

> what is a valid schema?

Given what is said above I think that for us a valid schema (to be used in the `value` function) can be defined as (more or less):

```js
function validSchema(schema) {
   return schema.type != null || schema.const != null || schema.enum != null || schema.oneOf?.reduce((acc, val)=> acc || validSchema(val), true)
}
```

with `const` or `enum` we can infer the type (number, string, object, or array) and the `oneOf` is just recursive.  I should have included all the possibilities looking at https://www.w3.org/TR/wot-thing-description11/#dataschema . Let me know if I missed something. 

P.s. I'd probably prefer that `const` and `enum` should always explicitly state the type but it could be just a warning.

**Comment by VigneshVSV** [comment]
Hi, I have following use case:

1)  nullable properties of fixed type - 

For example, I have the following property definition
```json

"state": {
      "title": "state",
      "description": "current state machine state if state machine present",
      "const": false,
      "readOnly": true,
      "writeOnly": false,
      "type": "string",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "forms": [
        {
          "href": https://laptop-f60cu35d:8083/spectrometer/ocean-optics/USB2000-plus/state,
          "op": "readproperty",
          "htv:methodName": "GET",
          "contentType": "application/json"
        }
      ],
      "observable": false
    },
“
```

state is a string property, but it can optionally `None` (python) in certain user defined cases. So I would like to claim that its one of string or null. However node-wot client throws the following error 

```javascript

“

wot-bundle.min.js:69468 Uncaught (in promise) Error: Invalid value according to DataSchema
    at InteractionOutput.<anonymous> (wot-bundle.min.js:69468:23)
    at Generator.next (<anonymous>)
    at fulfilled (wot-bundle.min.js:69369:58)
```

Since one of says the type can be more than one, if I skip the type field altogether, 

```
"state": {
      "title": "state",
      "description": "current state machine state if state machine present",
      "const": false,
      "readOnly": true,
      "writeOnly": false,
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "forms": [
        {
          "href": https://laptop-f60cu35d:8083/spectrometer/ocean-optics/USB2000-plus/state,
          "op": "readproperty",
          "htv:methodName": "GET",
          "contentType": "application/json"
        }
      ],
      "observable": false
    }
```

I get another error:

```javascript
wot-bundle.min.js:69453 Uncaught (in promise) Error: No schema type defined
    at InteractionOutput.<anonymous> (wot-bundle.min.js:69453:23)
    at Generator.next (<anonymous>)
    at wot-bundle.min.js:69372:71
    at new Promise (<anonymous>)
    at __awaiter (wot-bundle.min.js:69368:12)
    at InteractionOutput.value (wot-bundle.min.js:69438:16)
    at updateState (App.svelte:44:89)
```

So I am unable to use oneOf at all. 

2) Since already there is discussion about enum, I would (also) like to have of allowing multiple types either by self inference by node-wot or the possibility to use oneOf. Following is an example of a property:

```
background_correction": {
      "title": "background_correction",
      "description": "set \"AUTO\" for Seabreeze internal black level correction, \"CUSTOM\" to load your own background, or None for no background correction",
      "const": false,
      "default": null,
      "readOnly": false,
      "writeOnly": false,
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "enum": [
        "AUTO",
        "CUSTOM",
        null
      ],
      "forms": [
        {
          "href": "https://LAPTOP-F60CU35D:8083/spectrometer/ocean-optics/USB2000-plus/background-correction",
          "op": "readproperty",
          "htv:methodName": "GET",
          "contentType": "application/json"
        },
        {
          "href": "https://LAPTOP-F60CU35D:8083/spectrometer/ocean-optics/USB2000-plus/background-correction",
          "op": "writeproperty",
          "htv:methodName": "PUT",
          "contentType": "application/json"
        }
      ],
      "observable": false
```

Since my allowed values are "AUTO", "CUSTOM" and None, the type should be one of string or null.  If I set the type field, enum is broken, if I set enum I cannot set type field.

**Comment by danielpeintner** [comment]
I did not look into it more closely but I think you assume that `"type": "null"`  means a value can be null/undefined/optional.
This is not the case. In JSON schema validation this means that the value MUST be `"null"`

Maybe https://github.com/w3c/wot-thing-description/issues/1234 is relevant.

**Comment by VigneshVSV** [comment]
Also serializing None to "null" instead of null does not make sense.

**Comment by egekorkan** [comment]
This issue got diverted a bit but @VigneshVSV 's problem is not about null. null should not be represented as `"null"`, which is a string. It is the same issue above that node-wot always expects a `type` keyword

**Comment by VigneshVSV** [comment]
Yes a plain null also raises an issue:

```json
"state": {
      "title": "state",
      "description": "current state machine state if state machine present",
      "const": false,
      "readOnly": true,
      "writeOnly": false,
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": null
        }
      ],
      "forms": [
        {
          "href": "https://LAPTOP-F60CU35D:8083/spectrometer/ocean-optics/USB2000-plus/state",
          "op": "readproperty",
          "htv:methodName": "GET",
          "contentType": "application/json"
        }
      ],
      "observable": false
    }

```

the TD playground says:

> data/properties/state/oneOf/1/type must be string

**Comment by egekorkan** [comment]
Yes the value of type must be a string, I meant the payloads which are delivered. Those have to be `null`. Once #1279 is merged, you can disable validation and your issue should disappear for a while. In the long term, node-wot should not do schema validation in this restrictive way. You can find me in Discord and I can further explain.

**Comment by egekorkan** [comment]
By the way, this issue shows up even for our test thing: plugfest.thingweb.io:8083/testthing -> The void actions simply do not work

**Comment by danielpeintner** [comment]
> By the way, this issue shows up even for our test thing: http://plugfest.thingweb.io:8083/testthing -> The void actions simply do not work

I see, POST  http://plugfest.thingweb.io:8083/testthing/actions/void-void reports `No schema defined`
Anyhow, this has been fixed and the node-wot on http://plugfest.thingweb.io seems to be old.

I tried it locally and it works fine
