### ISSUE TITLE
BUG: Error when exposing a Thing because "structuredClone" is not defined

### ISSUE THREAD

**Issue by idilsezgin** [eclipse-thingweb/node-wot#1252]
Whenever I try to expose a Thing, I get this error
```bash
const tdSchemaCopy = structuredClone(tdSchema);
                             ^

ReferenceError: structuredClone is not defined
    at Function.createExposeThingInitSchema (..\node_modules\@node-wot\core\dist\helpers.js:182:30)
    at Object.<anonymous> (..\TestingTD\node_modules\@node-wot\core\dist\helpers.js:317:49)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (..\TestingTD\node_modules\@node-wot\core\dist\exposed-thing.js:51:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```
I checked and `structuredClone` is not defined in helpers.ts but also in consumed-thing.ts and http-server.ts (See below)
 https://github.com/eclipse-thingweb/node-wot/blob/0b7b108a0de0477dffd5d9d258fe90ca509a86d7/packages/core/src/helpers.ts#L223

https://github.com/eclipse-thingweb/node-wot/blob/0b7b108a0de0477dffd5d9d258fe90ca509a86d7/packages/core/src/consumed-thing.ts#L368

https://github.com/eclipse-thingweb/node-wot/blob/0b7b108a0de0477dffd5d9d258fe90ca509a86d7/packages/binding-http/src/http-server.ts#L323

Confirmed with @FadySalama

**Comment by danielpeintner** [comment]
Mhh, are you using a very old version of node or what is the context you are using it?

In https://github.com/eclipse-thingweb/node-wot/pull/1105 we introduced "structuredClone" and partly reverted it in https://github.com/eclipse-thingweb/node-wot/pull/1152 because we were running into issues.

Proposal to @JKRhb and others
I would create a helper function `Helpers.structuredClone()` that for now uses the old fashion cloning until we are sure the official `structuredClone()` does no longer cause issues. We can  point all places to this helper function...

relates to https://github.com/eclipse-thingweb/node-wot/issues/1153

**Comment by danielpeintner** [comment]
@idilsezgin can you tell us which Node.js version you are using?

**Comment by FadySalama** [comment]
@danielpeintner I can tell you tomorrow, as @idilsezgin is going on vacation
